spring.application.name=backend
server.port=8081
firebase.project-id=g7-angular-2026

# ==================== EMAIL ====================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aler98825@gmail.com
spring.mail.password=bnpozfujrllmbrbxo

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


firebase.service-account-path=g7-angular-2026-firebase-adminsdk-fbsvc-2055ce7ae5.json
